module.exports = [
	{
		id: 1,
		title: 'Amizade',
		icon: 'FaUsers',
		stringId: 'friendship',
	},
	{
		id: 2,
  	title: 'Amor e Romance',
		icon: 'FaHeartbeat',
		stringId: 'love-and-romance',
  },
  {
		id: 3,
    title: 'Carros e Motos',
		icon: 'FaCarAlt',
		stringId: 'cars-and-motorbikes',
  },
  {
		id: 4,
  	title: 'Cidades',
		icon: 'FaCity',
		stringId: 'cities',
	},
	{
		id: 5,
		title: 'Compra e Venda',
		icon: 'FaCommentDollar',
		stringId: 'buy-and-sell',
	},
	{
		id: 6,
		title: 'Concursos',
		icon: 'FaBook',
		stringId: 'contests',
	},
	{
		id: 7,
		title: 'Desenhos e Animes',
		icon: 'FaWolfPackBattalion',
		stringId: 'drawings-and-anime',
	},
	{
		id: 8,
		title: 'Educação',
		icon: 'FaGraduationCap',
		stringId: 'education',
	},
	{
		id: 9,
		title: 'Emagrecimento e Perda de peso',
		icon: 'FaRunning',
		stringId: 'slimming-and-weight-loss',
	},
	{
		id: 10,
		title: 'Esportes',
		icon: 'FaFootballBall',
		stringId: 'sports',
	},
	{
		id: 11,
		title: 'Eventos',
		icon: 'FaCalendarAlt',
		stringId: 'events',
	},
	{
		id: 12,
		title: 'Fãs',
		icon: 'FaNapster',
		stringId: 'fans',
	},
	{
		id: 13,
		title: 'Figurinhas e Stickers',
		icon: 'FaJenkins',
		stringId: 'stickers',
	},
	{
		id: 14,
		title: 'Filmes e Séries',
		icon: 'FaFilm',
		stringId: 'movies-and-series',
	},
	{
		id: 15,
		title: 'Frases e Mensagens',
		icon: 'FaFont',
		stringId: 'phrases-and-messages',
	},
	{
		id: 16,
		title: 'Futebol',
		icon: 'FaVolleyballBall',
		stringId: 'soccer',
	},
	{
		id: 17,
		title: 'Games e Jogos',
		icon: 'FaGamepad',
		stringId: 'games',
	},
	{
		id: 18,
		title: 'Ganhar Dinheiro',
		icon: 'FaMoneyBillAlt',
		stringId: 'make-money',
	},
	{
		id: 19,
		title: 'Imobiliária',
		icon: 'FaHome',
		stringId: 'real-estate',
	},
	{
		id: 20,
		title: 'Investimentos e Finanças',
		icon: 'FaChartBar',
		stringId: 'investments-and-finance',
	},
	{
		id: 21,
		title: 'Links',
		icon: 'FaExternalLinkAlt',
		stringId: 'links',
	},
	{
		id: 22,
		title: 'Memes, Engraçados e Zoeira',
		icon: 'FaGrinTongueSquint',
		stringId: 'funny',
	},
	{
		id: 23,
		title: 'Moda e Beleza',
		icon: 'FaTshirt',
		stringId: 'fashion-and-beauty',
	},
	{
		id: 24,
		title: 'Música',
		icon: 'FaMusic',
		stringId: 'music',
	},
	{
		id: 25,
		title: 'Namoro',
		icon: 'FaGrinHearts',
		stringId: 'dating',
	},
	{
		id: 27,
		title: 'Negócios e Empreendedorismo',
		icon: 'FaBusinessTime',
		stringId: 'business-and-entrepreneurship',
	},
	{
		id: 28,
		title: 'Notícias',
		icon: 'FaRegNewspaper',
		stringId: 'news',
	},
	{
		id: 29,
		title: 'Outros',
		icon: 'FaEllipsisH',
		stringId: 'others',
	},
	{
		id: 30,
		title: 'Política',
		icon: 'FaLandmark',
		stringId: 'policy',
	},
	{
		id: 31,
		title: 'Profissões',
		icon: 'FaUserTie',
		stringId: 'occupations',
	},
	{
		id: 32,
		title: 'Receitas',
		icon: 'FaUtensils',
		stringId: 'recipes',
	},
	{
		id: 33,
		title: 'Redes Sociais',
		icon: 'FaHashtag',
		stringId: 'social-media',
	},
	{
		id: 34,
		title: 'Religião',
		icon: 'FaChurch',
		stringId: 'religion',
	},
	{
		id: 35,
		title: 'Tecnologia',
		icon: 'FaLaptopCode',
		stringId: 'technology',
	},
	{
		id: 36,
		title: 'TV',
		icon: 'FaTv',
		stringId: 'tv',
	},
	{
		id: 37,
		title: 'Vagas de Emprego',
		icon: 'FaChalkboardTeacher',
		stringId: 'jobs',
	},
	{
		id: 38,
		title: 'Viagem e Turismo',
		icon: 'FaPlane',
		stringId: 'travel-and-tourism',
	},
	{
		id: 39,
		title: 'Videos',
		icon: 'FaYoutube',
		stringId: 'videos',
	},
];
